import { useEffect,useState } from 'react';
import { Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '../../src/lib/supabase';
import { SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY } from '../../src/config';
export default function NewSale(){const [customers,setCustomers]=useState<any[]>([]);const [products,setProducts]=useState<any[]>([]);const [warehouses,setWarehouses]=useState<any[]>([]);const [customer,setCustomer]=useState('');const [product,setProduct]=useState('');const [warehouse,setWarehouse]=useState('');const [qty,setQty]=useState('1');const [price,setPrice]=useState('');const [loading,setLoading]=useState(false);
useEffect(()=>{(async()=>{const [c,p,w]=await Promise.all([supabase.from('customers').select('id,name').eq('is_active',true).order('name').limit(100),supabase.from('products').select('id,name,sale_price').eq('is_active',true).order('name').limit(100),supabase.from('warehouses').select('id,name').eq('is_active',true).order('name')]);setCustomers(c.data??[]);setProducts(p.data??[]);setWarehouses(w.data??[]);if(w.data?.[0])setWarehouse(w.data[0].id)})()},[]);
async function save(){if(!product||!warehouse||!qty){Alert.alert('Eksik bilgi','Ürün, depo ve miktar gerekli.');return}const p=products.find(x=>x.id===product);const unit=price?Number(price):Number(p?.sale_price||0);setLoading(true);const {data:{session}}=await supabase.auth.getSession();if(!session){setLoading(false);router.replace('/login');return}const r=await fetch(`${SUPABASE_URL}/functions/v1/secure-rpc`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({action:'create_sale_with_price',args:{p_customer_id:customer||null,p_warehouse_id:warehouse,p_product_id:product,p_quantity:Number(qty),p_unit_price:unit,p_payment_type:'Vadeli',p_due_date:null,p_notes:null}})});const result=await r.json();setLoading(false);if(!r.ok){Alert.alert('Satış kaydedilemedi',result.error||'Bir hata oluştu.');return}Alert.alert('Başarılı','Satış kaydedildi.');router.back()}
return <ScrollView style={styles.page} contentContainerStyle={{paddingBottom:40}}><Text style={styles.title}>Yeni satış</Text><Text style={styles.label}>Müşteri</Text><View style={styles.choices}>{customers.slice(0,20).map(x=><Pressable key={x.id} onPress={()=>setCustomer(x.id)} style={[styles.choice,customer===x.id&&styles.selected]}><Text>{x.name}</Text></Pressable>)}</View><Text style={styles.label}>Ürün</Text><View style={styles.choices}>{products.slice(0,20).map(x=><Pressable key={x.id} onPress={()=>{setProduct(x.id);setPrice(String(x.sale_price||''))}} style={[styles.choice,product===x.id&&styles.selected]}><Text>{x.name}</Text></Pressable>)}</View><Text style={styles.label}>Miktar</Text><TextInput style={styles.input} keyboardType="decimal-pad" value={qty} onChangeText={setQty}/><Text style={styles.label}>Birim fiyat</Text><TextInput style={styles.input} keyboardType="decimal-pad" value={price} onChangeText={setPrice}/><Text style={styles.label}>Depo</Text><View style={styles.choices}>{warehouses.map(x=><Pressable key={x.id} onPress={()=>setWarehouse(x.id)} style={[styles.choice,warehouse===x.id&&styles.selected]}><Text>{x.name}</Text></Pressable>)}</View><Pressable style={styles.button} onPress={save} disabled={loading}><Text style={styles.buttonText}>{loading?'Kaydediliyor...':'Satışı kaydet'}</Text></Pressable></ScrollView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#f7f8fa',padding:16},title:{fontSize:26,fontWeight:'800',marginBottom:20},label:{fontWeight:'700',marginTop:12,marginBottom:7},choices:{gap:7},choice:{backgroundColor:'#fff',padding:13,borderRadius:12,borderWidth:1,borderColor:'#e5e7eb'},selected:{borderColor:'#111827',backgroundColor:'#eef2ff'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5e7eb',borderRadius:12,padding:13,fontSize:16},button:{backgroundColor:'#111827',padding:16,borderRadius:14,alignItems:'center',marginTop:22},buttonText:{color:'#fff',fontWeight:'800'}});
