from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')
s=re.sub(r'<script id="carbonerp-v20-customer-profile">.*?</script>\s*', '', s, count=1, flags=re.S)
s=re.sub(r'<script id="carbonerp-v20-customer-statement">.*?</script>\s*', '', s, count=1, flags=re.S)
script=r'''<script id="carbonerp-v20-customer-module">
(function(){
 const E=window.esc||function(x){return String(x??'')};
 const M=window.money||function(x){return Number(x||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})+' TL'};
 const activeSale=function(s){return (s.status||'active')!=='cancelled'};
 const activeCol=function(c){return (c.status||'active')!=='cancelled'};
 const val=function(id){const e=document.getElementById(id);return e?e.value.trim():''};
 const inp=function(id,label,value,type){return '<div class="field"><label>'+E(label)+'</label><input id="'+id+'" type="'+(type||'text')+'" value="'+E(value??'')+'"></div>'};
 const sel=function(id,label,value,opts){return '<div class="field"><label>'+E(label)+'</label><select id="'+id+'">'+opts.map(function(o){return '<option value="'+E(o)+'" '+(String(value??'')===String(o)?'selected':'')+'>'+E(o)+'</option>'}).join('')+'</select></div>'};
 function stats(id){
  const ss=(data.sales||[]).filter(function(s){return s.customer_id===id&&activeSale(s)});
  const cc=(data.collections||[]).filter(function(c){return c.customer_id===id&&activeCol(c)});
  const sales=ss.reduce(function(a,s){return a+Number(s.total||0)},0);
  const cols=cc.reduce(function(a,c){return a+Number(c.amount||0)},0);
  const overdue=ss.filter(function(s){return s.due_date&&s.due_date<today()&&saleOutstanding(s)>0}).reduce(function(a,s){return a+saleOutstanding(s)},0);
  return {sales:sales,cols:cols,open:Math.max(0,sales-cols),overdue:overdue};
 }
 function statement(id){
  const rows=[];let balance=0;
  (data.sales||[]).filter(function(s){return s.customer_id===id}).forEach(function(s){const cancel=!activeSale(s),qty=(s.sale_items||[]).reduce(function(a,i){return a+Number(i.quantity||0)},0);rows.push({d:s.sale_date||'',t:cancel?'İptal Satış':'Satış',r:String(s.id||'').slice(0,8).toUpperCase(),x:qty.toLocaleString('tr-TR')+' kg · '+(s.payment_type||'')+(s.due_date?' · Vade '+s.due_date:''),debit:cancel?0:Number(s.total||0),credit:0,status:cancel?'İptal':'Aktif',due:s.due_date||''})});
  (data.collections||[]).filter(function(c){return c.customer_id===id}).forEach(function(c){const cancel=!activeCol(c);rows.push({d:c.collection_date||'',t:cancel?'İptal Tahsilat':'Tahsilat',r:String(c.id||'').slice(0,8).toUpperCase(),x:c.payment_type||c.description||'Tahsilat',debit:0,credit:cancel?0:Number(c.amount||0),status:cancel?'İptal':'Aktif',due:''})});
  rows.sort(function(a,b){return String(a.d).localeCompare(String(b.d))});
  if(!rows.length)return '<div class="empty">Henüz cari hareket bulunmuyor.</div>';
  let body='';rows.forEach(function(r){balance+=r.debit-r.credit;const late=r.due&&r.due<today()&&r.debit>0&&balance>0?daysLate(r.due):0;body+='<tr><td>'+E(r.d)+'</td><td><b>'+E(r.t)+'</b><br><small>'+E(r.r)+'</small></td><td>'+E(r.x)+'</td><td>'+(r.debit?M(r.debit):'-')+'</td><td>'+(r.credit?M(r.credit):'-')+'</td><td>'+M(balance)+'</td><td>'+E(r.status)+(late?' · '+late+' gün gecikmiş':'')+'</td></tr>'});
  return '<div class="toolbar"><span class="status">'+rows.length+' hareket</span><button class="btn secondary" onclick="printCustomerStatement(\''+id+'\')">🖨️ Ekstre Yazdır</button></div><div style="overflow:auto"><table><tr><th>Tarih</th><th>İşlem</th><th>Açıklama</th><th>Borç</th><th>Alacak</th><th>Bakiye</th><th>Durum</th></tr>'+body+'</table></div>';
 }
 window.customerTable=function(){
  if(!(data.customers||[]).length)return '<div class="empty">Henüz müşteri yok.</div>';let body='';
  data.customers.forEach(function(c){const st=stats(c.id);body+='<tr><td><b>'+E(c.name)+'</b><br><small>'+E(c.customer_code||'')+'</small></td><td>'+E(c.phone||'-')+'</td><td>'+E(c.customer_type||'Diğer')+'</td><td>'+M(st.sales)+'</td><td>'+M(st.cols)+'</td><td class="'+(st.open>0?'warning':'positive')+'">'+M(st.open)+'</td><td><button class="btn secondary" onclick="customerDetail(\''+c.id+'\')">Detay</button> <button class="btn secondary" onclick="customerEdit(\''+c.id+'\')">Düzenle</button></td></tr>'});
  return '<table><tr><th>Müşteri</th><th>Telefon</th><th>Tip</th><th>Toplam Satış</th><th>Tahsilat</th><th>Cari</th><th></th></tr>'+body+'</table>';
 };
 window.customerDetail=function(id){
  const c=(data.customers||[]).find(function(x){return x.id===id});if(!c)return alert('Müşteri bulunamadı.');const st=stats(id);
  modalbox.innerHTML='<div class="toolbar"><div><h2 style="margin:0">'+E(c.name)+'</h2><div class="status">'+E(c.customer_code||'Kod yok')+' · '+E(c.customer_type||'Diğer')+'</div></div><div class="actions" style="margin:0"><button class="btn secondary" onclick="customerEdit(\''+id+'\')">Düzenle</button><button class="btn secondary" onclick="openCollectionForCustomer(\''+id+'\')">Tahsilat Gir</button><button class="btn secondary" onclick="closeModal()">Kapat</button></div></div>'+'<div class="cards"><div class="card"><small>Toplam Satış</small><div class="value">'+M(st.sales)+'</div></div><div class="card"><small>Toplam Tahsilat</small><div class="value positive">'+M(st.cols)+'</div></div><div class="card"><small>Güncel Cari</small><div class="value '+(st.open>0?'warning':'positive')+'">'+M(st.open)+'</div></div><div class="card"><small>Vadesi Geçmiş</small><div class="value '+(st.overdue>0?'danger':'positive')+'">'+M(st.overdue)+'</div></div></div>'+'<div class="panel"><h2>İletişim ve Vergi</h2><table><tr><td>Yetkili</td><td>'+E(c.contact_person||'-')+'</td><td>Telefon</td><td>'+E(c.phone||'-')+'</td></tr><tr><td>Alternatif</td><td>'+E(c.alternate_phone||'-')+'</td><td>WhatsApp</td><td>'+E(c.whatsapp||'-')+'</td></tr><tr><td>E-posta</td><td>'+E(c.email||'-')+'</td><td>Vergi No</td><td>'+E(c.tax_number||'-')+'</td></tr><tr><td>Vergi Dairesi</td><td>'+E(c.tax_office||'-')+'</td><td>E-Fatura</td><td>'+E(c.e_invoice_type||'-')+'</td></tr></table></div>'+'<div class="panel" style="margin-top:14px"><h2>Ticari ve Teslimat</h2><table><tr><td>Ödeme</td><td>'+E(c.default_payment_type||'-')+'</td><td>Vade</td><td>'+Number(c.default_due_days||0)+' gün</td></tr><tr><td>Kredi Limiti</td><td>'+M(c.credit_limit||0)+'</td><td>İskonto</td><td>%'+Number(c.discount_rate||0).toFixed(2)+'</td></tr><tr><td>Özel Fiyat</td><td>'+(c.special_price!=null?M(c.special_price)+'/kg':'Yok')+'</td><td>Min. Sipariş</td><td>'+Number(c.minimum_order_kg||0).toLocaleString('tr-TR')+' kg</td></tr><tr><td>Teslimat Adresi</td><td colspan="3">'+E(c.delivery_address||c.address||'-')+' '+E(c.delivery_city||c.city||'')+' '+E(c.delivery_district||c.district||'')+'</td></tr><tr><td>Teslimat Notu</td><td colspan="3">'+E(c.delivery_notes||'-')+'</td></tr></table></div>'+'<div class="panel" style="margin-top:14px"><h2>Cari Ekstre</h2>'+statement(id)+'</div>'+'<div class="panel" style="margin-top:14px"><h2>Notlar</h2><div style="white-space:pre-wrap">'+E(c.notes||'Not yok.')+'</div></div>';
  modal.classList.add('open');
 };
 window.customerEdit=function(id){
  const c=(data.customers||[]).find(function(x){return x.id===id});if(!c)return;
  const types=['Restaurant','Kasap','Market','Diğer'],pay=['Peşin','Havale/EFT','Kredi Kartı','Vadeli'];
  modalbox.innerHTML='<h2>Müşteri Düzenle</h2><div class="formgrid">'+inp('ce_name','İşletme / Müşteri Adı',c.name)+inp('ce_code','Müşteri Kodu',c.customer_code)+inp('ce_contact','Yetkili Kişi',c.contact_person)+sel('ce_type','Müşteri Tipi',c.customer_type||'Diğer',types)+inp('ce_phone','Telefon',c.phone,'tel')+inp('ce_alt','Alternatif Telefon',c.alternate_phone,'tel')+inp('ce_whatsapp','WhatsApp',c.whatsapp,'tel')+inp('ce_email','E-posta',c.email,'email')+inp('ce_website','Web Sitesi',c.website)+sel('ce_pref','İletişim Tercihi',c.contact_preference||'Fark etmez',['Telefon','WhatsApp','E-posta','Fark etmez'])+inp('ce_tax','Vergi No',c.tax_number)+inp('ce_office','Vergi Dairesi',c.tax_office)+inp('ce_invoice_title','Fatura Unvanı',c.invoice_title)+sel('ce_einvoice','E-Fatura',c.e_invoice_type||'E-Arşiv',['E-Arşiv','E-Fatura','Kağıt Fatura'])+inp('ce_city','İl',c.city)+inp('ce_district','İlçe',c.district)+inp('ce_postal','Posta Kodu',c.postal_code)+inp('ce_invoice_address','Fatura Adresi',c.invoice_address||c.address)+inp('ce_delivery_address','Teslimat Adresi',c.delivery_address||c.address)+inp('ce_delivery_city','Teslimat İl',c.delivery_city||c.city)+inp('ce_delivery_district','Teslimat İlçe',c.delivery_district||c.district)+inp('ce_delivery_region','Teslimat Bölgesi',c.delivery_region)+inp('ce_delivery_days','Teslimat Günleri',c.delivery_days)+inp('ce_delivery_time','Teslimat Saati',c.delivery_time)+inp('ce_delivery_notes','Teslimat Notu',c.delivery_notes)+sel('ce_payment','Varsayılan Ödeme',c.default_payment_type||'Vadeli',pay)+inp('ce_due','Vade Günü',c.default_due_days||0,'number')+inp('ce_limit','Kredi Limiti',c.credit_limit||0,'number')+inp('ce_discount','İskonto %',c.discount_rate||0,'number')+inp('ce_group','Müşteri Grubu',c.customer_group)+inp('ce_price_group','Özel Fiyat Grubu',c.price_group)+inp('ce_special','Özel Kg Fiyatı',c.special_price??'','number')+inp('ce_min_kg','Minimum Sipariş Kg',c.minimum_order_kg||0,'number')+inp('ce_rep','Satış Temsilcisi',c.sales_representative)+inp('ce_notes','Notlar',c.notes)+'</div><div class="actions"><button class="btn secondary" onclick="customerDetail(\''+id+'\')">Geri</button><button class="btn primary" onclick="saveCustomerEdit(\''+id+'\')">Kaydet</button></div>';
 };
 window.saveCustomerEdit=async function(id){try{const payload={name:val('ce_name'),customer_code:val('ce_code')||null,contact_person:val('ce_contact')||null,customer_type:val('ce_type')||'Diğer',phone:val('ce_phone')||null,alternate_phone:val('ce_alt')||null,whatsapp:val('ce_whatsapp')||null,email:val('ce_email')||null,website:val('ce_website')||null,contact_preference:val('ce_pref')||null,tax_number:val('ce_tax')||null,tax_office:val('ce_office')||null,invoice_title:val('ce_invoice_title')||null,e_invoice_type:val('ce_einvoice')||null,city:val('ce_city')||null,district:val('ce_district')||null,postal_code:val('ce_postal')||null,invoice_address:val('ce_invoice_address')||null,delivery_address:val('ce_delivery_address')||null,delivery_city:val('ce_delivery_city')||null,delivery_district:val('ce_delivery_district')||null,delivery_region:val('ce_delivery_region')||null,delivery_days:val('ce_delivery_days')||null,delivery_time:val('ce_delivery_time')||null,delivery_notes:val('ce_delivery_notes')||null,default_payment_type:val('ce_payment')||'Vadeli',default_due_days:Number(val('ce_due')||0),credit_limit:Number(val('ce_limit')||0),discount_rate:Number(val('ce_discount')||0),customer_group:val('ce_group')||null,price_group:val('ce_price_group')||null,special_price:val('ce_special')===''?null:Number(val('ce_special')),minimum_order_kg:Number(val('ce_min_kg')||0),sales_representative:val('ce_rep')||null,notes:val('ce_notes')||null,updated_at:new Date().toISOString(),updated_by:currentUser?.id||null};if(!payload.name)throw new Error('Müşteri adı zorunludur.');const q=await client.from('customers').update(payload).eq('id',id);if(q.error)throw q.error;await loadData();customerDetail(id)}catch(e){alert(msg(e))}};
 window.openCustomer=function(){modalbox.innerHTML='<h2>Yeni Müşteri</h2><div class="formgrid">'+inp('cn_name','İşletme / Müşteri Adı')+inp('cn_code','Müşteri Kodu')+inp('cn_contact','Yetkili Kişi')+sel('cn_type','Müşteri Tipi','Restaurant',['Restaurant','Kasap','Market','Diğer'])+inp('cn_phone','Telefon','tel')+inp('cn_alt','Alternatif Telefon','tel')+inp('cn_whatsapp','WhatsApp','tel')+inp('cn_email','E-posta','','email')+inp('cn_tax','Vergi No')+inp('cn_office','Vergi Dairesi')+inp('cn_invoice_title','Fatura Unvanı')+sel('cn_einvoice','E-Fatura','E-Arşiv',['E-Arşiv','E-Fatura','Kağıt Fatura'])+inp('cn_city','İl')+inp('cn_district','İlçe')+inp('cn_postal','Posta Kodu')+inp('cn_invoice_address','Fatura Adresi')+inp('cn_delivery_address','Teslimat Adresi')+inp('cn_delivery_city','Teslimat İl')+inp('cn_delivery_district','Teslimat İlçe')+inp('cn_delivery_region','Teslimat Bölgesi')+inp('cn_delivery_days','Teslimat Günleri')+inp('cn_delivery_time','Teslimat Saati')+inp('cn_delivery_notes','Teslimat Notu')+sel('cn_payment','Varsayılan Ödeme','Vadeli',['Peşin','Havale/EFT','Kredi Kartı','Vadeli'])+inp('cn_due','Vade Günü','0','number')+inp('cn_limit','Kredi Limiti','0','number')+inp('cn_discount','İskonto %','0','number')+inp('cn_group','Müşteri Grubu')+inp('cn_price_group','Özel Fiyat Grubu')+inp('cn_special','Özel Kg Fiyatı','','number')+inp('cn_min_kg','Minimum Sipariş Kg','0','number')+inp('cn_rep','Satış Temsilcisi')+inp('cn_notes','Notlar')+'</div><div class="actions"><button class="btn secondary" onclick="closeModal()">İptal</button><button class="btn primary" onclick="saveCustomerClean()">Kaydet</button></div>';modal.classList.add('open')};
 window.saveCustomerClean=async function(){try{const payload={name:val('cn_name'),customer_code:val('cn_code')||null,contact_person:val('cn_contact')||null,customer_type:val('cn_type')||'Diğer',phone:val('cn_phone')||null,alternate_phone:val('cn_alt')||null,whatsapp:val('cn_whatsapp')||null,email:val('cn_email')||null,tax_number:val('cn_tax')||null,tax_office:val('cn_office')||null,invoice_title:val('cn_invoice_title')||null,e_invoice_type:val('cn_einvoice')||null,city:val('cn_city')||null,district:val('cn_district')||null,postal_code:val('cn_postal')||null,invoice_address:val('cn_invoice_address')||null,delivery_address:val('cn_delivery_address')||null,delivery_city:val('cn_delivery_city')||null,delivery_district:val('cn_delivery_district')||null,delivery_region:val('cn_delivery_region')||null,delivery_days:val('cn_delivery_days')||null,delivery_time:val('cn_delivery_time')||null,delivery_notes:val('cn_delivery_notes')||null,default_payment_type:val('cn_payment')||'Vadeli',default_due_days:Number(val('cn_due')||0),credit_limit:Number(val('cn_limit')||0),discount_rate:Number(val('cn_discount')||0),customer_group:val('cn_group')||null,price_group:val('cn_price_group')||null,special_price:val('cn_special')===''?null:Number(val('cn_special')),minimum_order_kg:Number(val('cn_min_kg')||0),sales_representative:val('cn_rep')||null,notes:val('cn_notes')||null,is_active:true,updated_at:new Date().toISOString(),updated_by:currentUser?.id||null};if(!payload.name)throw new Error('Müşteri adı zorunludur.');const q=await client.from('customers').insert(payload);if(q.error)throw q.error;await loadData();closeModal();show('customers')}catch(e){alert(msg(e))}};
 window.printCustomerStatement=function(id){const c=(data.customers||[]).find(function(x){return x.id===id});if(!c)return;const st=stats(id),w=window.open('','_blank');if(!w)return;w.document.write('<html><head><title>'+E(c.name)+' Cari Ekstre</title><style>body{font-family:Arial}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:6px}th{background:#f3f3f3}.summary{display:flex;gap:10px}.box{border:1px solid #ddd;padding:10px}</style></head><body><h1>'+E(c.name)+'</h1><div class="summary"><div class="box">Satış: '+M(st.sales)+'</div><div class="box">Tahsilat: '+M(st.cols)+'</div><div class="box">Cari: '+M(st.open)+'</div><div class="box">Vadesi Geçmiş: '+M(st.overdue)+'</div></div>'+statement(id)+'</body></html>');w.document.close();setTimeout(function(){w.print()},150)};
})();
</script>'''
s=s.replace('</body>',script+'\n</body>',1)
p.write_text(s,encoding='utf-8')
