import { useEffect,useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { supabase } from '../../src/lib/supabase';

export default function CustomerDetail(){ const {id}=useLocalSearchParams<{id:string}>(); const [customer,setCustomer]=useState<any>(); const [sales,setSales]=useState<any[]>([]); const [collections,setCollections]=useState<any[]>([]); const [opening,setOpening]=useState<any[]>([]);
 useEffect(()=>{ if(!id)return; (async()=>{const c=await supabase.from('customers').select('*').eq('id',id).single(); setCustomer(c.data); const s=await supabase.from('sales').select('id,sale_date,total,status,payment_type').eq('customer_id',id).order('sale_date',{ascending:false}).limit(30); setSales(s.data??[]); const col=await supabase.from('collections').select('id,collection_date,amount,payment_type,status').eq('customer_id',id).order('collection_date',{ascending:false}).limit(30); setCollections(col.data??[]); const ob=await supabase.from('customer_opening_balances').select('id,entry_date,amount,direction,description').eq('customer_id',id).order('entry_date',{ascending:false}); setOpening(ob.data??[])})()},[id]);
 if(!customer)return <View style={styles.center}><ActivityIndicator/></View>;
 const totalSales=sales.filter(x=>x.status==='active').reduce((a,x)=>a+Number(x.total||0),0); const totalCollections=collections.filter(x=>x.status==='active').reduce((a,x)=>a+Number(x.amount||0),0); const openingDebit=opening.filter(x=>x.direction==='debit').reduce((a,x)=>a+Number(x.amount||0),0); const openingCredit=opening.filter(x=>x.direction==='credit').reduce((a,x)=>a+Number(x.amount||0),0); const balance=openingDebit-openingCredit+totalSales-totalCollections;
 return <ScrollView style={styles.page} contentContainerStyle={{paddingBottom:30}}><Text style={styles.name}>{customer.name}</Text><Text style={styles.meta}>{customer.customer_code??'Kod yok'} • {customer.phone??'Telefon yok'}</Text><View style={styles.balance}><Text style={styles.label}>Cari bakiye</Text><Text style={styles.amount}>{balance.toLocaleString('tr-TR',{minimumFractionDigits:2})} ₺</Text></View><View style={styles.grid}><Info label="Kredi limiti" value={`${Number(customer.credit_limit||0).toLocaleString('tr-TR')} ₺`}/><Info label="Şehir" value={customer.city||'—'}/><Info label="Ödeme" value={customer.default_payment_type||'—'}/><Info label="Vade" value={`${customer.default_due_days||0} gün`}/></View><Text style={styles.section}>Son satışlar</Text>{sales.map(x=><View style={styles.row} key={x.id}><Text style={styles.rowMain}>{x.sale_date}</Text><Text>{Number(x.total||0).toLocaleString('tr-TR')} ₺</Text></View>)}<Text style={styles.section}>Son tahsilatlar</Text>{collections.map(x=><View style={styles.row} key={x.id}><Text style={styles.rowMain}>{x.collection_date}</Text><Text>{Number(x.amount||0).toLocaleString('tr-TR')} ₺</Text></View>)}</ScrollView> }
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#f7f8fa',padding:18},center:{flex:1,justifyContent:'center',alignItems:'center'},name:{fontSize:25,fontWeight:'800'},meta:{color:'#6b7280',marginTop:4},balance:{backgroundColor:'#111827',borderRadius:18,padding:20,marginTop:18,marginBottom:12},label:{color:'#6b7280'},amount:{color:'#fff',fontSize:27,fontWeight:'800',marginTop:5},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},info:{backgroundColor:'#fff',borderRadius:14,padding:14,width:'48%',borderWidth:1,borderColor:'#e5e7eb'},infoValue:{fontWeight:'700',fontSize:15,marginTop:5},section:{fontSize:18,fontWeight:'800',marginTop:24,marginBottom:9},row:{backgroundColor:'#fff',borderRadius:12,padding:14,marginBottom:7,flexDirection:'row',justifyContent:'space-between'},rowMain:{fontWeight:'600'}});
